# Generated by Django 5.2.13 on 2026-04-27 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='is_completed',
            new_name='is_done',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='weight_record',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='date',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='is_public',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='progress',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
